"""Mark foreign keys in model and rename indexes

Revision ID: 3afbcc77e96b
Revises: a46409493594
Create Date: 2021-12-16 20:10:10.408687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3afbcc77e96b'
down_revision = 'a46409493594'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_40711_citation_cited_opinion_id', table_name='citation')
    op.drop_index('idx_40711_citation_citing_opinion_id', table_name='citation')
    op.create_index(op.f('ix_citation_cited_opinion_id'), 'citation', ['cited_opinion_id'], unique=False)
    op.create_index(op.f('ix_citation_citing_opinion_id'), 'citation', ['citing_opinion_id'], unique=False)
    op.create_foreign_key(None, 'citation', 'opinion', ['cited_opinion_id'], ['resource_id'])
    op.create_foreign_key(None, 'citation', 'opinion', ['citing_opinion_id'], ['resource_id'])
    op.drop_index('idx_40753_clustercitation_cited_cluster_id', table_name='clustercitation')
    op.drop_index('idx_40753_clustercitation_citing_cluster_id', table_name='clustercitation')
    op.create_index(op.f('ix_clustercitation_cited_cluster_id'), 'clustercitation', ['cited_cluster_id'], unique=False)
    op.create_index(op.f('ix_clustercitation_citing_cluster_id'), 'clustercitation', ['citing_cluster_id'], unique=False)
    op.create_foreign_key(None, 'clustercitation', 'cluster', ['citing_cluster_id'], ['resource_id'])
    op.create_foreign_key(None, 'clustercitation', 'cluster', ['cited_cluster_id'], ['resource_id'])
    op.drop_index('idx_40705_opinion_cluster_id', table_name='opinion')
    op.create_index(op.f('ix_opinion_cluster_id'), 'opinion', ['cluster_id'], unique=False)
    op.drop_index('opinionparenthetical_cited_opinion_id', table_name='opinionparenthetical')
    op.drop_index('opinionparenthetical_citing_opinion_id', table_name='opinionparenthetical')
    op.create_index(op.f('ix_opinionparenthetical_cited_opinion_id'), 'opinionparenthetical', ['cited_opinion_id'], unique=False)
    op.create_index(op.f('ix_opinionparenthetical_citing_opinion_id'), 'opinionparenthetical', ['citing_opinion_id'], unique=False)
    op.create_foreign_key(None, 'opinionparenthetical', 'opinion', ['cited_opinion_id'], ['resource_id'])
    op.create_foreign_key(None, 'opinionparenthetical', 'opinion', ['citing_opinion_id'], ['resource_id'])
    op.drop_index('idx_40750_similarity_opinion_a_id', table_name='similarity')
    op.drop_index('idx_40750_similarity_opinion_b_id', table_name='similarity')
    op.create_index(op.f('ix_similarity_opinion_a_id'), 'similarity', ['opinion_a_id'], unique=False)
    op.create_index(op.f('ix_similarity_opinion_b_id'), 'similarity', ['opinion_b_id'], unique=False)
    op.create_foreign_key(None, 'similarity', 'opinion', ['opinion_b_id'], ['resource_id'])
    op.create_foreign_key(None, 'similarity', 'opinion', ['opinion_a_id'], ['resource_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'similarity', type_='foreignkey')
    op.drop_constraint(None, 'similarity', type_='foreignkey')
    op.drop_index(op.f('ix_similarity_opinion_b_id'), table_name='similarity')
    op.drop_index(op.f('ix_similarity_opinion_a_id'), table_name='similarity')
    op.create_index('idx_40750_similarity_opinion_b_id', 'similarity', ['opinion_b_id'], unique=False)
    op.create_index('idx_40750_similarity_opinion_a_id', 'similarity', ['opinion_a_id'], unique=False)
    op.drop_constraint(None, 'opinionparenthetical', type_='foreignkey')
    op.drop_constraint(None, 'opinionparenthetical', type_='foreignkey')
    op.drop_index(op.f('ix_opinionparenthetical_citing_opinion_id'), table_name='opinionparenthetical')
    op.drop_index(op.f('ix_opinionparenthetical_cited_opinion_id'), table_name='opinionparenthetical')
    op.create_index('opinionparenthetical_citing_opinion_id', 'opinionparenthetical', ['citing_opinion_id'], unique=False)
    op.create_index('opinionparenthetical_cited_opinion_id', 'opinionparenthetical', ['cited_opinion_id'], unique=False)
    op.drop_index(op.f('ix_opinion_cluster_id'), table_name='opinion')
    op.create_index('idx_40705_opinion_cluster_id', 'opinion', ['cluster_id'], unique=False)
    op.drop_constraint(None, 'clustercitation', type_='foreignkey')
    op.drop_constraint(None, 'clustercitation', type_='foreignkey')
    op.drop_index(op.f('ix_clustercitation_citing_cluster_id'), table_name='clustercitation')
    op.drop_index(op.f('ix_clustercitation_cited_cluster_id'), table_name='clustercitation')
    op.create_index('idx_40753_clustercitation_citing_cluster_id', 'clustercitation', ['citing_cluster_id'], unique=False)
    op.create_index('idx_40753_clustercitation_cited_cluster_id', 'clustercitation', ['cited_cluster_id'], unique=False)
    op.drop_constraint(None, 'citation', type_='foreignkey')
    op.drop_constraint(None, 'citation', type_='foreignkey')
    op.drop_index(op.f('ix_citation_citing_opinion_id'), table_name='citation')
    op.drop_index(op.f('ix_citation_cited_opinion_id'), table_name='citation')
    op.create_index('idx_40711_citation_citing_opinion_id', 'citation', ['citing_opinion_id'], unique=False)
    op.create_index('idx_40711_citation_cited_opinion_id', 'citation', ['cited_opinion_id'], unique=False)
    # ### end Alembic commands ###
