"""Add indexes to resource_id columns

Revision ID: a46409493594
Revises: bc224e115ea0
Create Date: 2021-12-16 17:11:01.991014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a46409493594'
down_revision = 'bc224e115ea0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_cluster_resource_id'), 'cluster', ['resource_id'], unique=True)
    op.create_index(op.f('ix_opinion_resource_id'), 'opinion', ['resource_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_opinion_resource_id'), table_name='opinion')
    op.drop_index(op.f('ix_cluster_resource_id'), table_name='cluster')
    # ### end Alembic commands ###
